creation_rules: 
# public key: age1q285lp9dv2u0cdsr2feh4mth8yuv6g6cm4agcp69vly25p5nyqysm7dhz4
  - age: "age1q285lp9dv2u0cdsr2feh4mth8yuv6g6cm4agcp69vly25p5nyqysm7dhz4"
    encrypted_regex: "^(data|stringData|secret|secureJsonData)$"
    path_regex: ".*.yaml$"
