apiVersion: v1
kind: Secret
metadata:
    name: my-app-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:GwfgkPE=,iv:+Eb1IaV/Ys8v4aWq8DSaMJqmNsL9mqvH8M9GYJj2u40=,tag:1If43XrnnCwMo5umVqlWdA==,type:str]
    password: ENC[AES256_GCM,data:Y+c51QhJWCJIQIjPV0c=,iv:v/TB3nZY231bqW2aDmERPIoDq5EUFGyoYEgO8a9VFxU=,tag:wmRWyk51cXIR3RswjcFFSA==,type:str]
sops:
    lastmodified: "2026-01-04T23:03:09Z"
    mac: ENC[AES256_GCM,data:sk+GHoA23W/rtOl1YDdnCmhiqF7hV+t5cFIoGB76r0u2UuyKAOfRwGZbsS+tXVpD90id1fxdnnZc0o1fnU1nb71r+hfc1XqBNlTHK5TOBnmOn86M4UZ1XYTGRVFESb7kn+qiRMSKQ93X89Vhr4ObakkgAHSnlpGHpxzADv9Ewds=,iv:H/u6hJgxrteERfy79JkSCbEJUG94VfD8M9+DE8p2Erg=,tag:FIH2J8l+HTvLKsL5zNkGXg==,type:str]
    pgp:
        - created_at: "2026-01-04T23:03:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA+Vgg+SSwrYFAQv/a5yFnye8bQ3r9st+ZpVeonDanAEzbFRPkM16l5l9UpF8
            VkgJwmSH72BGMgsw6Xs4VuVrYhIULvBLHvOS+7OkxuLF2mXVcdzp9WEXkvijmSYi
            Z1SBnDCrvO0bOvRoybG0t/nkf0t0wxWAuusKJ6X2FLxlj6oiS7WZ7zDjcZYEcr/n
            OwFw3+e34iyo/sCAIlwL69PDPDH413nhYWcMDwTgq+PagslLCDsW2XAj29fWH/rl
            X/QS2y+b3UL9yOnqVqqgSmgSktS/gDBzPDpoK7BKGimhbNUTZxvZ3TaofdLtUdm5
            SuKvuTINYxjnyJU+T5K9IJcAlfshmPWINq1qZZtVeppNrZxn0ycjunZ6bZBRgK5I
            /LmmIWylCAwSg8c28MFSSLlKrUy3p17mCKjFcg9mXBq3PqekoIYR7/nBhxOZIyRt
            MQIQ+B9XZEH8JcsW4qqTVGxULxjbrp6sZMe/VjhJI8H7HGPHCu41NMF0MR8+dY0R
            YH2/kAFEPSIFfbnnjGo/1GgBCQIQbpXTV0kcbTMHnAzvgiIUtbcSMrH1DiHsviq8
            vl76wdKQct6b0gqlVe5xAwAnXnk6lYwe/TdkpOW0mbGJCpPBh2DhtK205f3dkrRn
            QYXTQOP4TxBkWyG2hZQT7l8lDblcHUa9MQ==
            =Rcc6
            -----END PGP MESSAGE-----
          fp: 42346B758B8C56E591F8E9E121A192CA6B87C596
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
