# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-app-secret
#   namespace: default
# type: Opaque
# stringData:
#   username: sidor
#   password: zxxxxxxxxx


apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
type: Opaque
stringData:
  age.key: |
    AGE-SECRET-KEY-1F38MM6TR0TNL4LEDUH3XAG96SJXYD7YSEV0ZW056N7A303P7NMGSD65W27

 