---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: flux-system
type: Opaque
stringData:
  token: eyJhIjoiNDNjMDQzMWJlNGFkOThkMzZkZGJiMmExMDM1NDVmNjEiLCJ0IjoiY2EzZWRlMWUtMDdlMS00MjAxLWE1ZTctMDA2MGU3OTgyZThkIiwicyI6Ik9ESmxPV1V4TlRVdFpUTmpaQzAwTnpVNExXRXpNR010TWpnMk5tWmhaVGRrWXpJMSJ9